apiVersion: packetwareapp.apps.packetware.net/v1
kind: App
metadata:
  name: my-app-1
spec:
  image: crccheck/hello-world
  resources:
    limits:
      memory: "1024Mi"
      cpu: "100m"
  locations:
    - tag: ashburn
      replicas:
        min: 1
        max: 1
  ports:
    - name: http-port
      port: 8000
      protocol: TCP
      targetPort: 8000
      private: false
  #volumeClaims:
  #  - claimName: my-longhorn-pvc
  #    mountPath: "/path/in/container"
